// Complete Handcrafted Products Database
const KALA_PRODUCTS = [
  {
    "id": "1",
    "slug": "flowers-1",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #1",
    "image": "images/products/flowers/img_1.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "2",
    "slug": "flowers-2",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #2",
    "image": "images/products/flowers/item_1.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "3",
    "slug": "flowers-3",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #3",
    "image": "images/products/flowers/img_2.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "4",
    "slug": "flowers-4",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #4",
    "image": "images/products/flowers/item_2.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "5",
    "slug": "flowers-5",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #5",
    "image": "images/products/flowers/img_3.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "6",
    "slug": "flowers-6",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #6",
    "image": "images/products/flowers/item_3.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "7",
    "slug": "flowers-7",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #7",
    "image": "images/products/flowers/img_4.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "8",
    "slug": "flowers-8",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #8",
    "image": "images/products/flowers/item_4.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "9",
    "slug": "flowers-9",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #9",
    "image": "images/products/flowers/img_5.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "10",
    "slug": "flowers-10",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #10",
    "image": "images/products/flowers/item_5.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "11",
    "slug": "flowers-11",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #11",
    "image": "images/products/flowers/img_6.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "12",
    "slug": "flowers-12",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #12",
    "image": "images/products/flowers/item_6.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "13",
    "slug": "flowers-13",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #13",
    "image": "images/products/flowers/img_7.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "14",
    "slug": "flowers-14",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #14",
    "image": "images/products/flowers/item_7.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "15",
    "slug": "flowers-15",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #15",
    "image": "images/products/flowers/img_8.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "16",
    "slug": "flowers-16",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #16",
    "image": "images/products/flowers/item_8.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "17",
    "slug": "flowers-17",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #17",
    "image": "images/products/flowers/img_9.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "18",
    "slug": "flowers-18",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #18",
    "image": "images/products/flowers/item_9.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "19",
    "slug": "flowers-19",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #19",
    "image": "images/products/flowers/img_10.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "20",
    "slug": "flowers-20",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #20",
    "image": "images/products/flowers/item_10.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "21",
    "slug": "flowers-21",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #21",
    "image": "images/products/flowers/img_11.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "22",
    "slug": "flowers-22",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #22",
    "image": "images/products/flowers/item_11.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "23",
    "slug": "flowers-23",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #23",
    "image": "images/products/flowers/img_12.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "24",
    "slug": "flowers-24",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #24",
    "image": "images/products/flowers/item_12.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "25",
    "slug": "flowers-25",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #25",
    "image": "images/products/flowers/img_13.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "26",
    "slug": "flowers-26",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #26",
    "image": "images/products/flowers/item_13.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "27",
    "slug": "flowers-27",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #27",
    "image": "images/products/flowers/img_14.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "28",
    "slug": "flowers-28",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #28",
    "image": "images/products/flowers/item_14.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "29",
    "slug": "flowers-29",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #29",
    "image": "images/products/flowers/img_15.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "30",
    "slug": "flowers-30",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #30",
    "image": "images/products/flowers/item_15.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "31",
    "slug": "flowers-31",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #31",
    "image": "images/products/flowers/img_16.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "32",
    "slug": "flowers-32",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #32",
    "image": "images/products/flowers/item_16.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "33",
    "slug": "flowers-33",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #33",
    "image": "images/products/flowers/img_17.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "34",
    "slug": "flowers-34",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #34",
    "image": "images/products/flowers/item_17.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "35",
    "slug": "flowers-35",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #35",
    "image": "images/products/flowers/img_18.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "36",
    "slug": "flowers-36",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #36",
    "image": "images/products/flowers/item_18.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "37",
    "slug": "flowers-37",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #37",
    "image": "images/products/flowers/img_19.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "38",
    "slug": "flowers-38",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #38",
    "image": "images/products/flowers/item_19.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "39",
    "slug": "flowers-39",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #39",
    "image": "images/products/flowers/img_20.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "40",
    "slug": "flowers-40",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #40",
    "image": "images/products/flowers/item_20.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "41",
    "slug": "flowers-41",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #41",
    "image": "images/products/flowers/img_21.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "42",
    "slug": "flowers-42",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #42",
    "image": "images/products/flowers/item_21.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "43",
    "slug": "flowers-43",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #43",
    "image": "images/products/flowers/img_22.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "44",
    "slug": "flowers-44",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #44",
    "image": "images/products/flowers/item_22.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "45",
    "slug": "flowers-45",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #45",
    "image": "images/products/flowers/img_23.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "46",
    "slug": "flowers-46",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #46",
    "image": "images/products/flowers/item_23.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "47",
    "slug": "flowers-47",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #47",
    "image": "images/products/flowers/img_24.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "48",
    "slug": "flowers-48",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #48",
    "image": "images/products/flowers/item_24.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "49",
    "slug": "flowers-49",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #49",
    "image": "images/products/flowers/img_25.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "50",
    "slug": "flowers-50",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #50",
    "image": "images/products/flowers/item_25.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "51",
    "slug": "flowers-51",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #51",
    "image": "images/products/flowers/img_26.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "52",
    "slug": "flowers-52",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #52",
    "image": "images/products/flowers/item_26.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "53",
    "slug": "flowers-53",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #53",
    "image": "images/products/flowers/img_27.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "54",
    "slug": "flowers-54",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #54",
    "image": "images/products/flowers/item_27.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "55",
    "slug": "flowers-55",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #55",
    "image": "images/products/flowers/img_28.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "56",
    "slug": "flowers-56",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #56",
    "image": "images/products/flowers/item_28.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "57",
    "slug": "flowers-57",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #57",
    "image": "images/products/flowers/img_29.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "58",
    "slug": "flowers-58",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #58",
    "image": "images/products/flowers/item_29.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "59",
    "slug": "flowers-59",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #59",
    "image": "images/products/flowers/img_30.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "60",
    "slug": "flowers-60",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #60",
    "image": "images/products/flowers/item_30.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "61",
    "slug": "flowers-61",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #61",
    "image": "images/products/flowers/img_31.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "62",
    "slug": "flowers-62",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #62",
    "image": "images/products/flowers/item_31.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "63",
    "slug": "flowers-63",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #63",
    "image": "images/products/flowers/img_32.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "64",
    "slug": "flowers-64",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #64",
    "image": "images/products/flowers/item_32.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "65",
    "slug": "flowers-65",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #65",
    "image": "images/products/flowers/img_33.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "66",
    "slug": "flowers-66",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #66",
    "image": "images/products/flowers/item_33.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "67",
    "slug": "flowers-67",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #67",
    "image": "images/products/flowers/img_34.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "68",
    "slug": "flowers-68",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #68",
    "image": "images/products/flowers/item_34.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "69",
    "slug": "flowers-69",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #69",
    "image": "images/products/flowers/img_35.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "70",
    "slug": "flowers-70",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #70",
    "image": "images/products/flowers/item_35.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "71",
    "slug": "flowers-71",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #71",
    "image": "images/products/flowers/img_36.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "72",
    "slug": "flowers-72",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #72",
    "image": "images/products/flowers/item_36.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "73",
    "slug": "flowers-73",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #73",
    "image": "images/products/flowers/img_37.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "74",
    "slug": "flowers-74",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #74",
    "image": "images/products/flowers/item_37.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "75",
    "slug": "flowers-75",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #75",
    "image": "images/products/flowers/img_38.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "76",
    "slug": "flowers-76",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #76",
    "image": "images/products/flowers/item_38.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "77",
    "slug": "flowers-77",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #77",
    "image": "images/products/flowers/img_39.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "78",
    "slug": "flowers-78",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #78",
    "image": "images/products/flowers/item_39.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "79",
    "slug": "flowers-79",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #79",
    "image": "images/products/flowers/img_40.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "80",
    "slug": "flowers-80",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #80",
    "image": "images/products/flowers/item_40.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "81",
    "slug": "flowers-81",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #81",
    "image": "images/products/flowers/img_41.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "82",
    "slug": "flowers-82",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #82",
    "image": "images/products/flowers/item_41.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "83",
    "slug": "flowers-83",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #83",
    "image": "images/products/flowers/img_42.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "84",
    "slug": "flowers-84",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #84",
    "image": "images/products/flowers/item_42.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "85",
    "slug": "flowers-85",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #85",
    "image": "images/products/flowers/img_43.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "86",
    "slug": "flowers-86",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #86",
    "image": "images/products/flowers/item_43.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "87",
    "slug": "flowers-87",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #87",
    "image": "images/products/flowers/img_44.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "88",
    "slug": "flowers-88",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #88",
    "image": "images/products/flowers/item_44.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "89",
    "slug": "flowers-89",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #89",
    "image": "images/products/flowers/img_45.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "90",
    "slug": "flowers-90",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #90",
    "image": "images/products/flowers/item_45.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "91",
    "slug": "flowers-91",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #91",
    "image": "images/products/flowers/img_46.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "92",
    "slug": "flowers-92",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #92",
    "image": "images/products/flowers/item_46.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "93",
    "slug": "flowers-93",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #93",
    "image": "images/products/flowers/img_47.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "94",
    "slug": "flowers-94",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #94",
    "image": "images/products/flowers/item_47.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "95",
    "slug": "flowers-95",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #95",
    "image": "images/products/flowers/img_48.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "96",
    "slug": "flowers-96",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #96",
    "image": "images/products/flowers/item_48.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "97",
    "slug": "flowers-97",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #97",
    "image": "images/products/flowers/img_49.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "98",
    "slug": "flowers-98",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #98",
    "image": "images/products/flowers/item_49.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "99",
    "slug": "flowers-99",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #99",
    "image": "images/products/flowers/img_50.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "100",
    "slug": "flowers-100",
    "categorySlug": "flowers",
    "category": "Flowers",
    "tag": "Crochet & Chenille Flowers",
    "title": "Flowers - Design #100",
    "image": "images/products/flowers/item_50.jpg",
    "price": "\u20b9299 - \u20b9899",
    "description": "Exquisitely hand-knitted floral masterpiece crafted with ultra-soft cotton/chenille yarn. Perfect for evergreen home decor, gifting, or personalized bouquets."
  },
  {
    "id": "101",
    "slug": "crochet-minion-keychain",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "\ud83d\udd14 Crochet Minion Keychain",
    "image": "images/products/key-chains/crochet-minion-keychain.jpg",
    "price": "\u20b9200/-",
    "description": "\ud83c\udf38 100% Handmade with soft, premium yarn\n\ud83d\udd11 Perfect for keys, bags & backpacks\n\ud83d\udca7 Washable & easy to maintain\n\ud83c\udf3f Lightweight, reusable & durable\n\ud83c\udfa8 Colour customisation available\n\ud83c\udf81 Perfect for gifting & return favours\n\nHandmade \u2022 Cute \u2022 Functional \u2022 Giftable \u2728"
  },
  {
    "id": "102",
    "slug": "key-chains-1",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #1",
    "image": "images/products/key-chains/img_1.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "103",
    "slug": "key-chains-2",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #2",
    "image": "images/products/key-chains/item_1.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "104",
    "slug": "key-chains-3",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #3",
    "image": "images/products/key-chains/img_2.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "105",
    "slug": "key-chains-4",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #4",
    "image": "images/products/key-chains/item_2.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "106",
    "slug": "key-chains-5",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #5",
    "image": "images/products/key-chains/img_3.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "107",
    "slug": "key-chains-6",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #6",
    "image": "images/products/key-chains/item_3.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "108",
    "slug": "key-chains-7",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #7",
    "image": "images/products/key-chains/img_4.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "109",
    "slug": "key-chains-8",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #8",
    "image": "images/products/key-chains/item_4.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "110",
    "slug": "key-chains-9",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #9",
    "image": "images/products/key-chains/img_5.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "111",
    "slug": "key-chains-10",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #10",
    "image": "images/products/key-chains/item_5.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "112",
    "slug": "key-chains-11",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #11",
    "image": "images/products/key-chains/img_6.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "113",
    "slug": "key-chains-12",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #12",
    "image": "images/products/key-chains/item_6.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "114",
    "slug": "key-chains-13",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #13",
    "image": "images/products/key-chains/img_7.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "115",
    "slug": "key-chains-14",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #14",
    "image": "images/products/key-chains/item_7.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "116",
    "slug": "key-chains-15",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #15",
    "image": "images/products/key-chains/img_8.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "117",
    "slug": "key-chains-16",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #16",
    "image": "images/products/key-chains/item_8.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "118",
    "slug": "key-chains-17",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #17",
    "image": "images/products/key-chains/img_9.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "119",
    "slug": "key-chains-18",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #18",
    "image": "images/products/key-chains/item_9.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "120",
    "slug": "key-chains-19",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #19",
    "image": "images/products/key-chains/img_10.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "121",
    "slug": "key-chains-20",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #20",
    "image": "images/products/key-chains/item_10.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "122",
    "slug": "key-chains-21",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #21",
    "image": "images/products/key-chains/img_11.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "123",
    "slug": "key-chains-22",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #22",
    "image": "images/products/key-chains/item_11.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "124",
    "slug": "key-chains-23",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #23",
    "image": "images/products/key-chains/img_12.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "125",
    "slug": "key-chains-24",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #24",
    "image": "images/products/key-chains/item_12.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "126",
    "slug": "key-chains-25",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #25",
    "image": "images/products/key-chains/img_13.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "127",
    "slug": "key-chains-26",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #26",
    "image": "images/products/key-chains/item_13.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "128",
    "slug": "key-chains-27",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #27",
    "image": "images/products/key-chains/img_14.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "129",
    "slug": "key-chains-28",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #28",
    "image": "images/products/key-chains/item_14.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "130",
    "slug": "key-chains-29",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #29",
    "image": "images/products/key-chains/img_15.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "131",
    "slug": "key-chains-30",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #30",
    "image": "images/products/key-chains/item_15.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "132",
    "slug": "key-chains-31",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #31",
    "image": "images/products/key-chains/img_16.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "133",
    "slug": "key-chains-32",
    "categorySlug": "key-chains",
    "category": "Key Chains",
    "tag": "Crochet Keychains & Charms",
    "title": "Key Chains - Design #32",
    "image": "images/products/key-chains/item_16.jpg",
    "price": "\u20b9149 - \u20b9349",
    "description": "Charming handcrafted crochet keychain & bag accessory made with vibrant yarn and sturdy metallic clip. Adds a touch of artisanal warmth to your daily carry."
  },
  {
    "id": "134",
    "slug": "potli-bags-1",
    "categorySlug": "potli-bags",
    "category": "Potli Bags",
    "tag": "Handcrafted Traditional Bags",
    "title": "Potli Bags - Design #1",
    "image": "images/products/potli-bags/item_1.jpg",
    "price": "\u20b9599 - \u20b91,299",
    "description": "Graceful festive potli bag with traditional crochet weaving, delicate drawstring tassels, and ample room for festive essentials and celebrations."
  },
  {
    "id": "135",
    "slug": "potli-bags-2",
    "categorySlug": "potli-bags",
    "category": "Potli Bags",
    "tag": "Handcrafted Traditional Bags",
    "title": "Potli Bags - Design #2",
    "image": "images/products/potli-bags/item_2.jpg",
    "price": "\u20b9599 - \u20b91,299",
    "description": "Graceful festive potli bag with traditional crochet weaving, delicate drawstring tassels, and ample room for festive essentials and celebrations."
  },
  {
    "id": "136",
    "slug": "potli-bags-3",
    "categorySlug": "potli-bags",
    "category": "Potli Bags",
    "tag": "Handcrafted Traditional Bags",
    "title": "Potli Bags - Design #3",
    "image": "images/products/potli-bags/item_3.jpg",
    "price": "\u20b9599 - \u20b91,299",
    "description": "Graceful festive potli bag with traditional crochet weaving, delicate drawstring tassels, and ample room for festive essentials and celebrations."
  },
  {
    "id": "137",
    "slug": "potli-bags-4",
    "categorySlug": "potli-bags",
    "category": "Potli Bags",
    "tag": "Handcrafted Traditional Bags",
    "title": "Potli Bags - Design #4",
    "image": "images/products/potli-bags/item_4.jpg",
    "price": "\u20b9599 - \u20b91,299",
    "description": "Graceful festive potli bag with traditional crochet weaving, delicate drawstring tassels, and ample room for festive essentials and celebrations."
  },
  {
    "id": "138",
    "slug": "potli-bags-5",
    "categorySlug": "potli-bags",
    "category": "Potli Bags",
    "tag": "Handcrafted Traditional Bags",
    "title": "Potli Bags - Design #5",
    "image": "images/products/potli-bags/item_5.jpg",
    "price": "\u20b9599 - \u20b91,299",
    "description": "Graceful festive potli bag with traditional crochet weaving, delicate drawstring tassels, and ample room for festive essentials and celebrations."
  },
  {
    "id": "139",
    "slug": "specs-holder-1",
    "categorySlug": "specs-holder",
    "category": "Specs Holder",
    "tag": "Crochet Eyewear Holders",
    "title": "Specs Holder - Design #1",
    "image": "images/products/specs-holder/item_1.jpg",
    "price": "\u20b9249 - \u20b9499",
    "description": "Practical and elegant handmade crochet specs strap/holder designed to protect and keep your eyeglasses or sunglasses conveniently accessible."
  },
  {
    "id": "140",
    "slug": "specs-holder-2",
    "categorySlug": "specs-holder",
    "category": "Specs Holder",
    "tag": "Crochet Eyewear Holders",
    "title": "Specs Holder - Design #2",
    "image": "images/products/specs-holder/item_2.jpg",
    "price": "\u20b9249 - \u20b9499",
    "description": "Practical and elegant handmade crochet specs strap/holder designed to protect and keep your eyeglasses or sunglasses conveniently accessible."
  },
  {
    "id": "141",
    "slug": "specs-holder-3",
    "categorySlug": "specs-holder",
    "category": "Specs Holder",
    "tag": "Crochet Eyewear Holders",
    "title": "Specs Holder - Design #3",
    "image": "images/products/specs-holder/item_3.jpg",
    "price": "\u20b9249 - \u20b9499",
    "description": "Practical and elegant handmade crochet specs strap/holder designed to protect and keep your eyeglasses or sunglasses conveniently accessible."
  },
  {
    "id": "142",
    "slug": "specs-holder-4",
    "categorySlug": "specs-holder",
    "category": "Specs Holder",
    "tag": "Crochet Eyewear Holders",
    "title": "Specs Holder - Design #4",
    "image": "images/products/specs-holder/item_4.jpg",
    "price": "\u20b9249 - \u20b9499",
    "description": "Practical and elegant handmade crochet specs strap/holder designed to protect and keep your eyeglasses or sunglasses conveniently accessible."
  },
  {
    "id": "143",
    "slug": "specs-holder-5",
    "categorySlug": "specs-holder",
    "category": "Specs Holder",
    "tag": "Crochet Eyewear Holders",
    "title": "Specs Holder - Design #5",
    "image": "images/products/specs-holder/item_5.jpg",
    "price": "\u20b9249 - \u20b9499",
    "description": "Practical and elegant handmade crochet specs strap/holder designed to protect and keep your eyeglasses or sunglasses conveniently accessible."
  },
  {
    "id": "144",
    "slug": "specs-holder-6",
    "categorySlug": "specs-holder",
    "category": "Specs Holder",
    "tag": "Crochet Eyewear Holders",
    "title": "Specs Holder - Design #6",
    "image": "images/products/specs-holder/item_6.jpg",
    "price": "\u20b9249 - \u20b9499",
    "description": "Practical and elegant handmade crochet specs strap/holder designed to protect and keep your eyeglasses or sunglasses conveniently accessible."
  },
  {
    "id": "145",
    "slug": "specs-holder-7",
    "categorySlug": "specs-holder",
    "category": "Specs Holder",
    "tag": "Crochet Eyewear Holders",
    "title": "Specs Holder - Design #7",
    "image": "images/products/specs-holder/item_7.jpg",
    "price": "\u20b9249 - \u20b9499",
    "description": "Practical and elegant handmade crochet specs strap/holder designed to protect and keep your eyeglasses or sunglasses conveniently accessible."
  },
  {
    "id": "146",
    "slug": "sunglass-cover-1",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #1",
    "image": "images/products/sunglass-cover/item_1.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "147",
    "slug": "sunglass-cover-2",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #2",
    "image": "images/products/sunglass-cover/item_2.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "148",
    "slug": "sunglass-cover-3",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #3",
    "image": "images/products/sunglass-cover/item_3.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "149",
    "slug": "sunglass-cover-4",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #4",
    "image": "images/products/sunglass-cover/item_4.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "150",
    "slug": "sunglass-cover-5",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #5",
    "image": "images/products/sunglass-cover/item_5.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "151",
    "slug": "sunglass-cover-6",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #6",
    "image": "images/products/sunglass-cover/item_6.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "152",
    "slug": "sunglass-cover-7",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #7",
    "image": "images/products/sunglass-cover/item_7.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "153",
    "slug": "sunglass-cover-8",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #8",
    "image": "images/products/sunglass-cover/item_8.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "154",
    "slug": "sunglass-cover-9",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #9",
    "image": "images/products/sunglass-cover/item_9.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "155",
    "slug": "sunglass-cover-10",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #10",
    "image": "images/products/sunglass-cover/item_10.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "156",
    "slug": "sunglass-cover-11",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #11",
    "image": "images/products/sunglass-cover/item_11.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "157",
    "slug": "sunglass-cover-12",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #12",
    "image": "images/products/sunglass-cover/item_12.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "158",
    "slug": "sunglass-cover-13",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #13",
    "image": "images/products/sunglass-cover/item_13.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "159",
    "slug": "sunglass-cover-14",
    "categorySlug": "sunglass-cover",
    "category": "Sunglass Cover",
    "tag": "Crochet Protective Covers",
    "title": "Sunglass Cover - Design #14",
    "image": "images/products/sunglass-cover/item_14.jpg",
    "price": "\u20b9299 - \u20b9599",
    "description": "Cushioned protective crochet sleeve tailored to guard sunglasses and mobile accessories against scratches and daily bumps in style."
  },
  {
    "id": "160",
    "slug": "tote-bags-1",
    "categorySlug": "tote-bags",
    "category": "Tote Bags",
    "tag": "Handcrafted Fashion Bags",
    "title": "Tote Bags - Design #1",
    "image": "images/products/tote-bags/item_1.jpg",
    "price": "\u20b9799 - \u20b91,899",
    "description": "Durable, eco-friendly handcrafted crochet tote bag made with reinforced premium yarn handles. Spacious and chic for casual outings or work."
  },
  {
    "id": "161",
    "slug": "tote-bags-2",
    "categorySlug": "tote-bags",
    "category": "Tote Bags",
    "tag": "Handcrafted Fashion Bags",
    "title": "Tote Bags - Design #2",
    "image": "images/products/tote-bags/item_2.jpg",
    "price": "\u20b9799 - \u20b91,899",
    "description": "Durable, eco-friendly handcrafted crochet tote bag made with reinforced premium yarn handles. Spacious and chic for casual outings or work."
  },
  {
    "id": "162",
    "slug": "tote-bags-3",
    "categorySlug": "tote-bags",
    "category": "Tote Bags",
    "tag": "Handcrafted Fashion Bags",
    "title": "Tote Bags - Design #3",
    "image": "images/products/tote-bags/item_3.jpg",
    "price": "\u20b9799 - \u20b91,899",
    "description": "Durable, eco-friendly handcrafted crochet tote bag made with reinforced premium yarn handles. Spacious and chic for casual outings or work."
  },
  {
    "id": "163",
    "slug": "tote-bags-4",
    "categorySlug": "tote-bags",
    "category": "Tote Bags",
    "tag": "Handcrafted Fashion Bags",
    "title": "Tote Bags - Design #4",
    "image": "images/products/tote-bags/item_4.jpg",
    "price": "\u20b9799 - \u20b91,899",
    "description": "Durable, eco-friendly handcrafted crochet tote bag made with reinforced premium yarn handles. Spacious and chic for casual outings or work."
  },
  {
    "id": "164",
    "slug": "toys-1",
    "categorySlug": "toys",
    "category": "Toys",
    "tag": "Crochet Amigurumi Toys",
    "title": "Toys - Design #1",
    "image": "images/products/toys/item_1.jpg",
    "price": "\u20b9399 - \u20b9799",
    "description": "Adorable handmade amigurumi crochet plush toy, knitted with baby-safe hypoallergenic soft yarn and filled with love."
  }
];
